[project]
name = "curling_tracker_backend"
version = "0.1.0"
description = "Tracks curling stones from video data."

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"